selenium-hub:
  image: selenium/hub
  container_name: selenium-hub
  ports:
    - "4444:4444"
chrome:
  image: selenium/node-chrome
  links:
    - selenium-hub:hub
firefox:
  image: selenium/node-firefox
  links:
    - selenium-hub:hub